apiVersion: batch/v1
kind: Job
metadata:
  name: multi-completion-parallel-batch-job
spec:
  completions: 10
  parallelism: 3
  template:
    metadata:
      labels:
        app: multi-completion-parallel-batch-job
    spec:
      restartPolicy: OnFailure
      containers:
        - name: main
          image: luksa/batch-job